use std::fs;
use std::path::PathBuf;

pub const APP_QUALIFIER: &str = "com";
pub const APP_ORGANIZATION: &str = "grokbridge";
pub const APP_NAME: &str = "desktop";

pub fn data_dir() -> Result<PathBuf, String> {
    let dir = dirs::data_dir()
        .ok_or_else(|| "cannot resolve user data dir".to_string())?
        .join("com.grokbridge.desktop");
    fs::create_dir_all(&dir).map_err(|e| format!("create data dir: {e}"))?;
    fs::create_dir_all(dir.join("data")).map_err(|e| format!("create db dir: {e}"))?;
    fs::create_dir_all(dir.join("logs")).map_err(|e| format!("create logs dir: {e}"))?;
    Ok(dir)
}

pub fn config_path() -> Result<PathBuf, String> {
    Ok(data_dir()?.join("config.yaml"))
}

pub fn sqlite_path() -> Result<PathBuf, String> {
    Ok(data_dir()?.join("data").join("grok-bridge.db"))
}

pub fn ensure_config(default_listen: &str, admin_password: &str) -> Result<PathBuf, String> {
    let path = config_path()?;
    if path.exists() {
        return Ok(path);
    }
    let sqlite = sqlite_path()?;
    let body = format!(
        r#"# Auto-generated by Grok Bridge Desktop
server:
  listen: "{listen}"

admin:
  password: "{password}"
  session_ttl: 24h

data:
  sqlite_path: "{sqlite}"

proxy:
  http_proxy: ""
  scheduling: "round_robin"
  max_concurrency: 0
  account_concurrency: 0
  retry:
    max_account_switches: 2
    max_transient_retries: 2
  log_bodies: "errors_only"
  log_retention_days: 30
  unknown_model: "passthrough"

models:
  - id: grok-4.5
  - id: grok-4.3
  - id: grok-3-mini

aliases:
  "claude-sonnet-4-20250514": "grok-4.5"
  "gpt-5": "grok-4.5"

xai: {{}}
"#,
        listen = default_listen,
        password = admin_password.replace('"', "\\\""),
        sqlite = sqlite.display().to_string().replace('\\', "\\\\"),
    );
    fs::write(&path, body).map_err(|e| format!("write config: {e}"))?;
    Ok(path)
}
